Update existing test for snapshots
singlestone/sugar pull request #159
Opened 2023-01-16 20:30 UTC by BwyattSSC

- Add vite.config.ts to individual modules

Added snapshot test coverage to existing test. Based on per review, will add additional test as needed.

## Description

## Related Issue

[ISSUE-xx](https://github.com/singlestone/sugar/issues/xx) (TBD)

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] I added a changeset via `yarn changeset` if my changes should be released.

2023-01-17 05:21 UTC, ToppleTheNun commented
> There is likely a cleaner way of handling this by extending a higher level vite.config.ts file but I haven't found anything on this quite yet.
The cleaner way to do this is to make a package like the tsup-config one: https://github.com/singlestone/sugar/blob/main/tools/tsup-config/src/index.ts

2023-02-01 19:07 UTC, BwyattSSC commented
Per conversation with @pcmart03 , moving this item to `Ready for Review`

Left `My code follow the code style of this project` unchecked as I wasn't sure what they were.
Left `My change requires a change to the documentation` and `I have updated documentation accordingly` for the time being. What information would we want to include as it pertains to running the test? Where should this information live?
Left `I added a changeset via yarn changeset if my changes should be released` unchecked as well as I don't believe it needed one but not sure.

2023-02-02 00:36 UTC, ToppleTheNun requested changes
One small requested change then we should be good.

2023-02-02 00:36 UTC, ToppleTheNun commented on tools/test-utils/package.json
> +  "license": "MIT",
Can you add `"private": true,` underneath the license field?

2023-02-02 14:20 UTC, BwyattSSC commented on tools/test-utils/package.json
> +  "license": "MIT",
Commit https://github.com/singlestone/sugar/pull/159/commits/07e91866a67634f0c8e085cdbbcf085004dcdf42 includes the requested changes.

2023-02-02 16:43 UTC, ToppleTheNun approved these changes

2023-02-02 16:43 UTC, merged